import os

# SECRET_KEY = os.environ["SECRET_KEY"]
# AWS_DEFAULT_REGION = os.environ["AWS_REGION"]
# AWS_COGNITO_DOMAIN = os.environ["AWS_COGNITO_DOMAIN"]
# AWS_COGNITO_USER_POOL_ID = os.environ["AWS_COGNITO_USER_POOL_ID"]
# AWS_COGNITO_USER_POOL_CLIENT_ID = os.environ["AWS_COGNITO_USER_POOL_CLIENT_ID"]
# AWS_COGNITO_USER_POOL_CLIENT_SECRET = os.environ["AWS_COGNITO_USER_POOL_CLIENT_SECRET"]
# AWS_COGNITO_REDIRECT_URL = os.environ['AWS_COGNITO_REDIRECT_URL']
#
# If debug
SECRET_KEY = '[XH6}NtBvnm8Ca=['
AWS_DEFAULT_REGION = 'us-east-1'
AWS_COGNITO_DOMAIN = 'auth.declan.xyz'
AWS_COGNITO_USER_POOL_ID = 'us-east-1_QTMWKAoW7'
AWS_COGNITO_USER_POOL_CLIENT_ID = 'v4udn42afflgsakb8t44nfte1'
AWS_COGNITO_USER_POOL_CLIENT_SECRET = '1abtmrumbvnk1no1og3e511q1jvp5hbv7t302i88dl6q037qc5ja'
AWS_COGNITO_REDIRECT_URL = 'https://panel.declan.xyz/login-callback'
